// Comprehensive relationship type definitions for WarmConnector

export const RELATIONSHIP_TYPES = {
  // Professional Relationships - Core
  COWORKER: 'coworker',
  MANAGER: 'manager',
  DIRECT_REPORT: 'direct_report',
  VENDOR_CLIENT: 'vendor_client',
  ADVISOR_ADVISEE: 'advisor_advisee',
  INDUSTRY_PEERS: 'industry_peers',
  
  // Professional Relationships - Advanced
  INVESTOR_ENTREPRENEUR: 'investor_entrepreneur',
  BOARD_MEMBER: 'board_member',
  BOARD_OBSERVER: 'board_observer',
  BOARD_ADVISOR: 'board_advisor',
  EXECUTIVE_ASSISTANT: 'executive_assistant',
  PROCUREMENT_VENDOR: 'procurement_vendor',
  CUSTOMER_SUCCESS: 'customer_success',
  ACCOUNT_MANAGER: 'account_manager',
  REGULATORY_COMPLIANCE: 'regulatory_compliance',
  MERGER_ACQUISITION_ALUMNI: 'merger_acquisition_alumni',
  CONFERENCE_SPEAKER: 'conference_speaker',
  CONFERENCE_ORGANIZER: 'conference_organizer',
  SPEAKER_BUREAU: 'speaker_bureau',
  CERTIFICATION_COHORT: 'certification_cohort',
  ACCELERATOR_COHORT: 'accelerator_cohort',
  PATENTS_COAUTHOR: 'patents_coauthor',
  PATENT_INVENTOR: 'patent_inventor',
  RESEARCH_COLLABORATOR: 'research_collaborator',
  PROJECT_COLLABORATOR: 'project_collaborator',
  INDUSTRY_ANALYST: 'industry_analyst',
  PRIVATE_EQUITY_NETWORK: 'private_equity_network',
  VENTURE_CAPITAL_NETWORK: 'venture_capital_network',
  
  // Educational Relationships
  EDUCATION: 'education',
  PROFESSOR_STUDENT: 'professor_student',
  THESIS_ADVISOR: 'thesis_advisor',
  STUDY_GROUP: 'study_group',
  
  // Family & Personal
  FAMILY: 'family',
  SPOUSE: 'spouse',
  SIBLING: 'sibling',
  PARENT_CHILD: 'parent_child',
  EXTENDED_FAMILY: 'extended_family',
  
  // Social & Community
  SOCIAL: 'social',
  FRIEND: 'friend',
  GREEK_LIFE: 'greek_life',
  HOMETOWN: 'hometown',
  NEIGHBORHOOD: 'neighborhood',
  RELIGIOUS_COMMUNITY: 'religious_community',
  HOBBY_CLUB: 'hobby_club',
  SPORTS_TEAM: 'sports_team',
  PARENTING_NETWORK: 'parenting_network',
  
  // Volunteer & Civic
  CHARITABLE_CAUSE: 'charitable_cause',
  POLITICAL_CAMPAIGN: 'political_campaign',
  VOLUNTEER_ORG: 'volunteer_org',
  BOARD_SERVICE: 'board_service',
  
  // Digital & Modern
  ONLINE_COMMUNITY: 'online_community',
  GAMING_GUILD: 'gaming_guild',
  CONTENT_CREATOR: 'content_creator',
  SOCIAL_MEDIA_INFLUENCER: 'social_media_influencer',
  OPEN_SOURCE_CONTRIBUTOR: 'open_source_contributor',
  MEETUP_ATTENDEE: 'meetup_attendee',
  
  // Life Transition & Specialized
  MILITARY_SERVICE: 'military_service',
  IMMIGRATION_COHORT: 'immigration_cohort',
  CAREER_TRANSITION: 'career_transition',
  LIFE_EVENT_SHARED: 'life_event_shared',
  
  // Contextual
  CUSTOMER_SUPPORT: 'customer_support',
  SALES_RELATIONSHIP: 'sales_relationship',
  RECRUITER_CANDIDATE: 'recruiter_candidate',
  LANDLORD_TENANT: 'landlord_tenant'
} as const;

export type RelationshipType = typeof RELATIONSHIP_TYPES[keyof typeof RELATIONSHIP_TYPES];

export const RELATIONSHIP_SUBTYPES = {
  // Manager subtypes
  DIRECT_MANAGER: 'direct_manager',
  SKIP_LEVEL_MANAGER: 'skip_level_manager',
  MATRIX_MANAGER: 'matrix_manager',
  FORMER_MANAGER: 'former_manager',
  
  // Advisor subtypes
  BOARD_ADVISOR: 'board_advisor',
  TECHNICAL_ADVISOR: 'technical_advisor',
  BUSINESS_MENTOR: 'business_mentor',
  CAREER_MENTOR: 'career_mentor',
  
  // Investment subtypes
  ANGEL_INVESTOR: 'angel_investor',
  VC_PARTNER: 'vc_partner',
  LP_INVESTOR: 'lp_investor',
  STARTUP_FOUNDER: 'startup_founder',
  
  // Family subtypes
  IMMEDIATE_FAMILY: 'immediate_family',
  EXTENDED_FAMILY: 'extended_family',
  IN_LAWS: 'in_laws',
  STEP_FAMILY: 'step_family',
  
  // Education subtypes
  CLASSMATE: 'classmate',
  ROOMMATE: 'roommate',
  STUDY_PARTNER: 'study_partner',
  ACADEMIC_COLLABORATOR: 'academic_collaborator',
  
  // Community subtypes
  NEIGHBOR: 'neighbor',
  CONGREGATION_MEMBER: 'congregation_member',
  CLUB_OFFICER: 'club_officer',
  TEAM_CAPTAIN: 'team_captain'
} as const;

export type RelationshipSubtype = typeof RELATIONSHIP_SUBTYPES[keyof typeof RELATIONSHIP_SUBTYPES];

// Relationship strength scoring guidelines
export const STRENGTH_LEVELS = {
  VERY_STRONG: { min: 90, max: 100, label: 'Very Strong' },
  STRONG: { min: 70, max: 89, label: 'Strong' },
  MODERATE: { min: 50, max: 69, label: 'Moderate' },
  WEAK: { min: 30, max: 49, label: 'Weak' },
  VERY_WEAK: { min: 1, max: 29, label: 'Very Weak' }
} as const;

// Default strength values by relationship type
export const DEFAULT_STRENGTHS: Record<RelationshipType, number> = {
  [RELATIONSHIP_TYPES.FAMILY]: 95,
  [RELATIONSHIP_TYPES.SPOUSE]: 100,
  [RELATIONSHIP_TYPES.SIBLING]: 90,
  [RELATIONSHIP_TYPES.PARENT_CHILD]: 95,
  [RELATIONSHIP_TYPES.MILITARY_SERVICE]: 85,
  [RELATIONSHIP_TYPES.ADVISOR_ADVISEE]: 80,
  [RELATIONSHIP_TYPES.BOARD_MEMBER]: 85,
  [RELATIONSHIP_TYPES.BOARD_OBSERVER]: 75,
  [RELATIONSHIP_TYPES.BOARD_ADVISOR]: 80,
  [RELATIONSHIP_TYPES.EXECUTIVE_ASSISTANT]: 90, // High value for C-suite access
  [RELATIONSHIP_TYPES.PROCUREMENT_VENDOR]: 70,
  [RELATIONSHIP_TYPES.CUSTOMER_SUCCESS]: 75,
  [RELATIONSHIP_TYPES.ACCOUNT_MANAGER]: 70,
  [RELATIONSHIP_TYPES.REGULATORY_COMPLIANCE]: 65,
  [RELATIONSHIP_TYPES.MERGER_ACQUISITION_ALUMNI]: 60,
  [RELATIONSHIP_TYPES.CONFERENCE_ORGANIZER]: 70,
  [RELATIONSHIP_TYPES.SPEAKER_BUREAU]: 65,
  [RELATIONSHIP_TYPES.PATENT_INVENTOR]: 80,
  [RELATIONSHIP_TYPES.INDUSTRY_ANALYST]: 75,
  [RELATIONSHIP_TYPES.PRIVATE_EQUITY_NETWORK]: 80,
  [RELATIONSHIP_TYPES.VENTURE_CAPITAL_NETWORK]: 80,
  [RELATIONSHIP_TYPES.PATENTS_COAUTHOR]: 85,
  [RELATIONSHIP_TYPES.RESEARCH_COLLABORATOR]: 75,
  [RELATIONSHIP_TYPES.COWORKER]: 65,
  [RELATIONSHIP_TYPES.MANAGER]: 70,
  [RELATIONSHIP_TYPES.DIRECT_REPORT]: 70,
  [RELATIONSHIP_TYPES.GREEK_LIFE]: 75,
  [RELATIONSHIP_TYPES.ACCELERATOR_COHORT]: 70,
  [RELATIONSHIP_TYPES.VENDOR_CLIENT]: 60,
  [RELATIONSHIP_TYPES.INDUSTRY_PEERS]: 45,
  [RELATIONSHIP_TYPES.EDUCATION]: 55,
  [RELATIONSHIP_TYPES.CONFERENCE_SPEAKER]: 40,
  [RELATIONSHIP_TYPES.ONLINE_COMMUNITY]: 35,
  [RELATIONSHIP_TYPES.MEETUP_ATTENDEE]: 30,
  [RELATIONSHIP_TYPES.SOCIAL]: 50,
  [RELATIONSHIP_TYPES.FRIEND]: 70,
  [RELATIONSHIP_TYPES.HOMETOWN]: 40,
  [RELATIONSHIP_TYPES.NEIGHBORHOOD]: 45,
  [RELATIONSHIP_TYPES.RELIGIOUS_COMMUNITY]: 60,
  [RELATIONSHIP_TYPES.HOBBY_CLUB]: 50,
  [RELATIONSHIP_TYPES.SPORTS_TEAM]: 55,
  [RELATIONSHIP_TYPES.PARENTING_NETWORK]: 65,
  [RELATIONSHIP_TYPES.CHARITABLE_CAUSE]: 55,
  [RELATIONSHIP_TYPES.POLITICAL_CAMPAIGN]: 50,
  [RELATIONSHIP_TYPES.VOLUNTEER_ORG]: 55,
  [RELATIONSHIP_TYPES.BOARD_SERVICE]: 75,
  [RELATIONSHIP_TYPES.GAMING_GUILD]: 40,
  [RELATIONSHIP_TYPES.CONTENT_CREATOR]: 45,
  [RELATIONSHIP_TYPES.SOCIAL_MEDIA_INFLUENCER]: 35,
  [RELATIONSHIP_TYPES.OPEN_SOURCE_CONTRIBUTOR]: 50,
  [RELATIONSHIP_TYPES.IMMIGRATION_COHORT]: 65,
  [RELATIONSHIP_TYPES.CAREER_TRANSITION]: 55,
  [RELATIONSHIP_TYPES.LIFE_EVENT_SHARED]: 60,
  [RELATIONSHIP_TYPES.INVESTOR_ENTREPRENEUR]: 70,
  [RELATIONSHIP_TYPES.BOARD_MEMBER]: 80,
  [RELATIONSHIP_TYPES.CERTIFICATION_COHORT]: 50,
  [RELATIONSHIP_TYPES.PROJECT_COLLABORATOR]: 65,
  [RELATIONSHIP_TYPES.PROFESSOR_STUDENT]: 60,
  [RELATIONSHIP_TYPES.THESIS_ADVISOR]: 75,
  [RELATIONSHIP_TYPES.STUDY_GROUP]: 45,
  [RELATIONSHIP_TYPES.EXTENDED_FAMILY]: 70,
  [RELATIONSHIP_TYPES.CUSTOMER_SUPPORT]: 35,
  [RELATIONSHIP_TYPES.SALES_RELATIONSHIP]: 40,
  [RELATIONSHIP_TYPES.RECRUITER_CANDIDATE]: 35,
  [RELATIONSHIP_TYPES.LANDLORD_TENANT]: 30
};

// Sensitivity levels for privacy controls
export const SENSITIVITY_LEVELS = {
  LOW: 'low',     // Public professional information
  MEDIUM: 'medium', // Semi-private, requires discretion
  HIGH: 'high'    // Highly sensitive, requires explicit consent
} as const;

export const RELATIONSHIP_SENSITIVITY: Record<RelationshipType, keyof typeof SENSITIVITY_LEVELS> = {
  [RELATIONSHIP_TYPES.PATENTS_COAUTHOR]: 'LOW',
  [RELATIONSHIP_TYPES.CONFERENCE_SPEAKER]: 'LOW',
  [RELATIONSHIP_TYPES.OPEN_SOURCE_CONTRIBUTOR]: 'LOW',
  [RELATIONSHIP_TYPES.EDUCATION]: 'LOW',
  [RELATIONSHIP_TYPES.COWORKER]: 'LOW',
  [RELATIONSHIP_TYPES.INDUSTRY_PEERS]: 'LOW',
  [RELATIONSHIP_TYPES.VENDOR_CLIENT]: 'MEDIUM',
  [RELATIONSHIP_TYPES.ADVISOR_ADVISEE]: 'MEDIUM',
  [RELATIONSHIP_TYPES.INVESTOR_ENTREPRENEUR]: 'MEDIUM',
  [RELATIONSHIP_TYPES.BOARD_MEMBER]: 'MEDIUM',
  [RELATIONSHIP_TYPES.CHARITABLE_CAUSE]: 'MEDIUM',
  [RELATIONSHIP_TYPES.FAMILY]: 'HIGH',
  [RELATIONSHIP_TYPES.SPOUSE]: 'HIGH',
  [RELATIONSHIP_TYPES.RELIGIOUS_COMMUNITY]: 'HIGH',
  [RELATIONSHIP_TYPES.POLITICAL_CAMPAIGN]: 'HIGH',
  [RELATIONSHIP_TYPES.MILITARY_SERVICE]: 'HIGH',
  [RELATIONSHIP_TYPES.IMMIGRATION_COHORT]: 'HIGH',
  [RELATIONSHIP_TYPES.PARENTING_NETWORK]: 'MEDIUM',
  [RELATIONSHIP_TYPES.NEIGHBORHOOD]: 'MEDIUM',
  [RELATIONSHIP_TYPES.SOCIAL]: 'MEDIUM',
  [RELATIONSHIP_TYPES.FRIEND]: 'MEDIUM',
  [RELATIONSHIP_TYPES.GREEK_LIFE]: 'MEDIUM',
  [RELATIONSHIP_TYPES.HOMETOWN]: 'MEDIUM',
  [RELATIONSHIP_TYPES.HOBBY_CLUB]: 'MEDIUM',
  [RELATIONSHIP_TYPES.SPORTS_TEAM]: 'MEDIUM',
  [RELATIONSHIP_TYPES.VOLUNTEER_ORG]: 'MEDIUM',
  [RELATIONSHIP_TYPES.BOARD_SERVICE]: 'MEDIUM',
  [RELATIONSHIP_TYPES.ONLINE_COMMUNITY]: 'LOW',
  [RELATIONSHIP_TYPES.GAMING_GUILD]: 'LOW',
  [RELATIONSHIP_TYPES.CONTENT_CREATOR]: 'LOW',
  [RELATIONSHIP_TYPES.SOCIAL_MEDIA_INFLUENCER]: 'LOW',
  [RELATIONSHIP_TYPES.MEETUP_ATTENDEE]: 'LOW',
  [RELATIONSHIP_TYPES.ACCELERATOR_COHORT]: 'LOW',
  [RELATIONSHIP_TYPES.CERTIFICATION_COHORT]: 'LOW',
  [RELATIONSHIP_TYPES.RESEARCH_COLLABORATOR]: 'LOW',
  [RELATIONSHIP_TYPES.PROJECT_COLLABORATOR]: 'MEDIUM',
  [RELATIONSHIP_TYPES.MANAGER]: 'MEDIUM',
  [RELATIONSHIP_TYPES.DIRECT_REPORT]: 'MEDIUM',
  [RELATIONSHIP_TYPES.PROFESSOR_STUDENT]: 'MEDIUM',
  [RELATIONSHIP_TYPES.THESIS_ADVISOR]: 'MEDIUM',
  [RELATIONSHIP_TYPES.STUDY_GROUP]: 'LOW',
  [RELATIONSHIP_TYPES.SIBLING]: 'HIGH',
  [RELATIONSHIP_TYPES.PARENT_CHILD]: 'HIGH',
  [RELATIONSHIP_TYPES.EXTENDED_FAMILY]: 'HIGH',
  [RELATIONSHIP_TYPES.CAREER_TRANSITION]: 'MEDIUM',
  [RELATIONSHIP_TYPES.LIFE_EVENT_SHARED]: 'MEDIUM',
  [RELATIONSHIP_TYPES.CUSTOMER_SUPPORT]: 'LOW',
  [RELATIONSHIP_TYPES.SALES_RELATIONSHIP]: 'MEDIUM',
  [RELATIONSHIP_TYPES.RECRUITER_CANDIDATE]: 'MEDIUM',
  [RELATIONSHIP_TYPES.LANDLORD_TENANT]: 'MEDIUM'
};